# Generated by Django 6.0.4 on 2026-04-13 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix (€)')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Image')),
                ('alcohol_type', models.CharField(choices=[('vin', 'Vin'), ('biere', 'Bière'), ('whisky', 'Whisky'), ('rhum', 'Rhum'), ('vodka', 'Vodka'), ('gin', 'Gin'), ('champagne', 'Champagne'), ('autre', 'Autre')], default='vin', max_length=20, verbose_name="Type d'alcool")),
                ('volume', models.CharField(blank=True, help_text='Ex: 75cl, 70cl', max_length=20, verbose_name='Volume')),
                ('alcohol_degree', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Degré d'alcool (%)")),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='Origine')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
    ]
